#!/bin/sh

# docker build -t nosweatframework/php:7.4 -f Dockerfile --build-arg "PHP_VERSION=7.4" .
# docker build -t nosweatframework/php:7.4-dev -f Dockerfile.dev --build-arg "PHP_VERSION=7.4" .

docker pull php:7.4-fpm
docker pull php:8.1-fpm
docker pull php:8.2-fpm

docker build -t nosweatframework/php:7.4 -f Dockerfile --build-arg "PHP_VERSION=7.4" .
docker build -t nosweatframework/php:8.1 -f Dockerfile --build-arg "PHP_VERSION=8.1" .
docker build -t nosweatframework/php:8.2 -f Dockerfile --build-arg "PHP_VERSION=8.2" .

# docker build -t nosweatframework/php:8.1 -f Dockerfile --build-arg "PHP_VERSION=8.1" .
# docker build -t nosweatframework/php:8.1-dev -f Dockerfile.dev --build-arg "PHP_VERSION=8.1" .
