ARG PHP_VERSION=8.1

FROM nosweatframework/php:${PHP_VERSION}

ARG USERNAME=php

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions xdebug xhprof

USER ${USERNAME}
